import pytest
from datetime import date
from decimal import Decimal
from typing import Optional


from src.repository import PostgresRepository
from src.services import record_new_transaction, record_new_account
from src import model
from tests.helpers.sample_data import (
    cash_account,
    petty_cash_account,
    base_salary_account,
)


def test_record_new_transaction(repo_with_data: PostgresRepository):
    """
    GIVEN a PostgresRepository with existing data and a valid Transaction object
    WHEN the record_new_transaction service is called with the repository and the Transaction object
    THEN the transaction should be successfully recorded in the database,
    and the transaction details and ledger entries should match the provided data.
    """
    transaction_date = date(2001, 6, 1)
    description = "Test services new trans"
    amount = Decimal("123.98")

    record_new_transaction(
        repo_with_data,
        transaction=model.Transaction(
            id=None,
            date=transaction_date,
            description=description,
            lines=[
                model.TransactionLine(
                    account=petty_cash_account,
                    amount=amount,
                    entry_type=model.EntryType.DEBIT,
                ),
                model.TransactionLine(
                    account=base_salary_account,
                    amount=amount,
                    entry_type=model.EntryType.CREDIT,
                ),
            ],
        ),
    )
    transaction_id = repo_with_data.get_max_transaction_id()

    assert repo_with_data.postgres_client.query(
        f"SELECT transaction_id, transaction_date, transaction_description FROM {repo_with_data.transactions_table} WHERE transaction_id = {transaction_id}"
    ) == [(transaction_id, transaction_date, description)]
    assert repo_with_data.postgres_client.query(
        f"SELECT transaction_id, account_id, entry_type_id, amount "
        f"FROM {repo_with_data.ledger_entries_table} "
        f"WHERE transaction_id = {transaction_id} ORDER BY entry_type_id"
    ) == [
        (transaction_id, base_salary_account.id, 1, amount),
        (transaction_id, petty_cash_account.id, 2, amount),
    ]


@pytest.mark.parametrize(
    "new_account_name, new_account_type, is_physical, is_archived, father_account",
    [
        ("New Savings Account", model.AccountType.ASSET, True, False, None),
        ("New Checking Account", model.AccountType.ASSET, True, False, cash_account),
    ],
)
def test_record_new_account(
    new_account_name: str,
    new_account_type: model.AccountType,
    is_physical: bool,
    is_archived: bool,
    father_account: Optional[model.Account],
    repo_with_data: PostgresRepository,
):
    """
    GIVEN a PostgresRepository and a new Account object
    WHEN the record_new_account service is called with the Account object
    THEN the account should be successfully recorded in the database,
    and its details should match the provided data.
    """
    new_account = model.Account(
        id=None,  # ID will be generated by the repository
        account_type=new_account_type,
        name=new_account_name,
        is_physical=is_physical,
        is_archived=is_archived,
        father_account=father_account,
    )

    record_new_account(repo_with_data, new_account)

    max_account_id = repo_with_data.get_max_account_id()
    retrieved_account_data = repo_with_data.postgres_client.query(
        f"SELECT account_id, account_type_id, account_name, is_physical, is_archived "
        f"FROM {repo_with_data.accounts_table} WHERE account_id = {max_account_id}"
    )

    assert len(retrieved_account_data) == 1
    assert retrieved_account_data[0] == (
        max_account_id,
        new_account_type.id,
        new_account_name,
        is_physical,
        is_archived,
    )
